#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

rm -r [0-9].*
rm -r [1-9]*
rm -r proc*
rm log.*

#------------------------------------------------------------------------------
